x-function: &basics
  networks:
    - testing_network

services:
  timefold-app:
    <<: *basics
    image: vehicle-routing
    ports:
      - '8080:8080'
    build:
      context: vehicle-routing
      dockerfile: ../docker/Dockerfile
    container_name: vehicle-routing
    hostname: vehicle-routing
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '2G'
        reservations:
          cpus: '4'
          memory: '2G'
    volumes:
      - ./data/results:/app/results:rw

  curl-app:
    <<: *basics
    image: curlimages/curl:latest
    container_name: curl-app
    hostname: curl-app
    volumes:
      - ./data/sample.json:/home/curl_user/sample.json
      - ./data/request_response.sh:/home/curl_user/request_response.sh
    command: >
      sh -c "
        ping -c 4 vehicle-routing &&
        /home/curl_user/request_response.sh"
    depends_on:
      timefold-app:
        condition: service_started

networks:
  testing_network:
    name: testing_default
